### ISSUE TITLE
Integrate with LiteLLM - Evaluate 100+LLMs, 92% faster 

### ISSUE THREAD

**Issue by ishaan-jaff** [jvroig/llm_localbench#1]
Hi @jvroig  I'm the maintainer of LiteLLM. we allow you to create a proxy server to call 100+ LLMs to make it easier to run benchmark / evals . 

**I'm making this issue because I believe LiteLLM makes it easier for you to run benchmarks and evaluate LLMs (I'd love your feedback if it does not)**

Try it here: https://docs.litellm.ai/docs/simple_proxy
https://github.com/BerriAI/litellm

## Creating a proxy server 
Ollama models
```shell
$ litellm --model ollama/llama2 --api_base http://localhost:11434
```

Hugging Face Models 
```shell
$ export HUGGINGFACE_API_KEY=my-api-key #[OPTIONAL]
$ litellm --model claude-instant-1
```

Anthropic 
```shell
$ export ANTHROPIC_API_KEY=my-api-key
$ litellm --model claude-instant-1
```
Palm

```shell
$ export PALM_API_KEY=my-palm-key
$ litellm --model palm/chat-bison
```

## Using to run an eval on lm harness:
```python
python3 -m lm_eval \
  --model openai-completions \
  --model_args engine=davinci \
  --task crows_pairs_english_age

```

**Comment by jvroig** [comment]
Thanks, maybe some other time in the future. 

llm_localbench is really just for running models locally as I play around with them, and not really to try to evaluate hosted models.

Closing for now.

**Comment by ishaan-jaff** [comment]
thanks for the feedback @jvroig can you help clarify this ? 
I noticed you were calling a deployed sagemaker endpoint 

https://github.com/jvroig/llm_localbench/blob/6e539d46e273cccd2b8b8caf2903672d1863e926/sagemaker_run.py#L71

**Comment by jvroig** [comment]
That's just an exceptional case - for models we want to investigate that absolutely can't be run locally (in this case, because it's part of the Llama 2 family, most of which can be ran locally in our machines), we just whipped up a quick script for a JumpStart endpoint so that we can have a 70B reference performance vs our smaller+quantized models. 

It's really not something that'll be expanded on or improved over time - or at least, that's not the goal so far.

**Comment by ishaan-jaff** [comment]
last question: why are you evaluating only local LLMs? (aren't the commercial APIs a lot better )

**Comment by jvroig** [comment]
It's simply my area of interest at the moment.
